### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by aammfe** [Mongo2Go/Mongo2Go#111]
Hello!!
thanks for this good repository.
I would like to ask few questions.

1- Is it a good idea to use mongo2go while Unit testing ones Intelligent repository (or Intelligent data layer) ?
2- please do a comparison in terms of feasibility and performance BW mongo2go and **"ephemeralForTests" storage engine** for unit testing.
[unit-testing-mongodb-queries](https://www.thomasb.fr/2017/12/unit-testing-mongodb-queries/)
3- can we use both at same time ?
4- what else do u recommend to unit test ones system with Intelligent repository (or Intelligent data layer) ?

**Comment by JohannesHoppe** [comment]
1. Mongo2Go is just a helpful wrapper so that you do not have to install the MongoDB server manually. The technologies used in higher layers should be irrelevant.
2. No, why should I do that?
3. I have no idea.
4. Same.

This is a tool that once helped me and I have made it open source so others can benefit. Beyond that, there is no obligation for me to invest more work than necessary.
