### ISSUE TITLE
A Way to dispose StartForDebugging

### ISSUE THREAD

**Issue by luizpalte** [Mongo2Go/Mongo2Go#151]
I need to have just one instance because of the number of tests I have, but I need to dispose of the database after all my tests. And I can't find on documentation a way to drop the database after my tests.

Can you help me?

**Comment by JohannesHoppe** [comment]
Should be doable:

https://github.com/Mongo2Go/Mongo2Go/blob/a908b765d4f37c0b8a895a8eec081d0c6b1d2dfc/src/Mongo2Go/MongoDbRunner.IDisposable.cs#L44C17-L47
```cs
if (_dataDirectoryWithPort != null)
{
    // finally clean up the data directory we created previously
    _fileSystem.DeleteFolder(_dataDirectoryWithPort);
}
```

Have you tried to specify a data directory (and the default port)?
If that works, then please report back. Because this line in `MongoDbRunner.cs` is a bit misleading then:

>  Only starts one single MongoDB instance (even on multiple calls), does not kill it, does not delete data
