### ISSUE TITLE
mongod.exe remains active after tests complete

### ISSUE THREAD

**Issue by Mardoxx** [Mongo2Go/Mongo2Go#33]
I'm using the default net core XUnit project, but targeting net461.

When I run several tests, sometimes mongod.exe instances remain active until I can terminate them.

I shall attempt to put together a small repro when I get time.

P.S. Any reason this is targeting net standard 1.6 instead of an earlier version?

**Comment by JohannesHoppe** [comment]
Right now the 1.x branch covers .NET 4.6.1, the 2.x branch covers the new .NET Standard.
Nobody has found the time to make a solution which works on both flavors. That's why! :-(

Please feel free to fix this and send a PR! :+1: 
We had this open a while ago:
https://github.com/Mongo2Go/Mongo2Go/issues/17

**Comment by Mardoxx** [comment]
Ahh right!

My tests seem to run fine otherwise. Just have to manually clean up any remaining mongod processes.

I may have a look in to this, it's a useful library. Certainly a lot easier than mocking IMongoDatabase, IAsyncCursor et al. !! 😄

**Comment by JohannesHoppe** [comment]
Just for the records:

If the process hangs endlessly the reason might be the following.
`runner.Dispose()` was not executed at the end of the test. See this: https://github.com/Mongo2Go/Mongo2Go/issues/54#issuecomment-428604330
