### ISSUE TITLE
Difference in performance between Start and StartForDebugging

### ISSUE THREAD

**Issue by dannyBies** [Mongo2Go/Mongo2Go#70]
Hi,

Thank you very much for this project, it has helped me out a lot!
While creating integration tests I have noticed that there is a significant performance hit when using MongoDbRunner.Start() versus MongoDbRunner.StartForDebugging().

I am running MongoDbRunner.Start() for every single test and I dispose the runner after the test has completed. For 23 integration tests this takes around 1 minute. If I change this to StartForDebugging my tests take around 3 seconds. 

I was wondering why there is such a big difference? And if there is something that I can setup to make my tests run faster with .Start().

Thanks!

**Comment by JohannesHoppe** [comment]
Thats by design

* `MongoDbRunner.Start()`starts a new MongoDB process AND does a clean up on dispose. Data will be erased
* `StartForDebugging` reuses the same same running MongoDB instance again and never does a cleanup. Data is not erased

Feel free to call whatever works for you if your tests are designed to be independent from each other. So you have to make sure that the data is in a predictable state before each test on your own!

Cheers!
