### ISSUE TITLE
Request for support of different versions of mongod server

### ISSUE THREAD

**Issue by nachiappannk** [Mongo2Go/Mongo2Go#74]
Hi,

Currently the Mongo2Go supports only one version of mongod server (ie is 4.0.3). Could we add support for different versions? It would be great if we can support different flavours such as RHEL or Ubuntu, etc...

I would like to high light some information here.
In javascript world, there are mongodb package downloaders that support this
https://www.npmjs.com/package/mongodb-prebuilt
https://www.npmjs.com/package/mongodb-download

These package facilitating downloading of mongodb server version from the "https://fastdl.mongodb.org" based on the target os version.

providing this flexibility would be great in C# world.

If you are okay with the idea, I can also work on getting the feature implemented. (I might need some information and help)

Regards,
Nachiappan

**Comment by JohannesHoppe** [comment]
I work a lot with NPM and there additional downloads are a huge problem. An example is node-sass. While the NPM download works, the binaries download often fails because of proxy problems. The proxy settings of Nuget (config file) are not the same as those of CURL (environment variables). Not to mention restrictive corporate networks where everything has to run exclusively on its own NPM server and there is no direct access to the Internet. It is one big mess.

BUT I wouldn't object to an additional Nuget package, e.g. "Mongo2Go Light". Here we could offer this functionality. You can build a PR for it, I like to host this Nuget package in this project. Unfortunately I don't have any capacities. It's up to you! 😉
